# Docker production config for redmine application
#
# Sets up a database, an nginx proxy, a smtp service, and the redmine application.
#
redmine:
  build: .
  links:
    - tmpdb:mysql
  
db:
  image: mysql
  volumes_from:
    - redminedbdata
  environment:
    - MYSQL_ROOT_PASSWORD=RedMineRoot
    - MYSQL_DATABASE=redmine
    - MYSQL_USER=redmine
    - MYSQL_PASSWORD=RedMine


